spring.application.name=cons-ub-prod-hor-kafka
server.port=8082

# Kafka Bootstrap Servers (override via env SPRING_KAFKA_BOOTSTRAP_SERVERS en Docker)
spring.kafka.bootstrap-servers=localhost:29092,localhost:39092,localhost:49092
